release-it- use bamper plugin, pyproject update poetry settings
RedHatQE/cloud-tools pull request #140
Opened 2023-07-31 13:50 UTC by oharan2

- Verified VERSION file
- Updated project metadata and dependencies
- Updated .release-it file `change-log` and `plugins` sections
- Updated `poetry.lock` according new changes

2023-07-31 20:51 UTC, myakove requested changes
Update the PR title and add more info

2023-07-31 20:51 UTC, myakove commented on pyproject.toml
> +# Ipython requires Python >=3.9
Please remove this comment, and set the project python to ^3.8

2023-07-31 20:51 UTC, myakove commented on pyproject.toml
> +files = ["VERSION"]
Need to be created and set the version there.

2023-07-31 20:51 UTC, myakove commented on pyproject.toml
>  readme = "README.md"
`authors = ["Meni Yakove", "Ruth Netser"]` missing email, please add

2023-08-02 07:23 UTC, oharan2 commented
/verified

2023-08-02 13:53 UTC, oharan2 commented
/verified

2023-08-03 10:12 UTC, rnetser approved these changes

2023-08-03 10:14 UTC, oharan2 commented
/verified

2023-08-03 10:16 UTC, rnetser approved these changes

2023-08-03 10:19 UTC, merged