add_script_s3_bucket_deletion
RedHatQE/cloud-tools pull request #2
Opened 2023-03-09 12:35 UTC by ILpinto

The main purpose of this script is to delete a bucket associated with a cluster
after the cluster is uninstalled

2023-03-09 13:14 UTC, ILpinto commented
/verified

2023-03-09 13:22 UTC, myakove requested changes

2023-03-09 13:22 UTC, myakove commented on aws/delete_s3_velero_bucket.py
> +    Returns:
No need to set `Returns` in docstring if the function do not retirn anything

2023-03-09 13:22 UTC, myakove commented on aws/delete_s3_velero_bucket.py
> +    require_env = ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"]
you also need to check `S3_CLUSTER` right? or remove line 14

2023-03-09 13:22 UTC, myakove commented on aws/delete_s3_velero_bucket.py
> +            LOGGER.error(
I would collect all the env that not set and log one error with the missing ones

2023-03-09 13:22 UTC, myakove commented on aws/delete_s3_velero_bucket.py
> +        None
Please remove all things that have `None` (`Args` in this case)

2023-03-09 13:22 UTC, myakove commented on aws/delete_s3_velero_bucket.py
> +        """
Why set the string with `"""` ?

2023-03-09 13:22 UTC, myakove commented on aws/delete_s3_velero_bucket.py
> +from ocp_utilities.logger import get_logger
Please set your own logger, do not use other modules logger

2023-03-12 08:11 UTC, ILpinto commented on aws/delete_s3_velero_bucket.py
> +    sys.exit(1)
refactor and add new method verify_env_variables_and_parameters

2023-03-12 09:40 UTC, closed without merging

2023-03-12 09:41 UTC, ILpinto commented
Moved https://github.com/RedHatQE/cloud-tools/pull/4